filter:
    paths:
        - 'inc/*'
        - '*'
    excluded_paths:
        - 'languages/*'
        - 'lib/*'
        - 'tests/*'
tools:
    php_mess_detector:
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
    php_analyzer:
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
        config:
            parameter_reference_check: { enabled: true }
            checkstyle: { enabled: true, no_trailing_whitespace: true, naming: { enabled: false, local_variable: '', abstract_class_name: '', utility_class_name: '', constant_name: '', property_name: '', method_name: '', parameter_name: '', interface_name: '', type_name: '', exception_name: '', isser_method_name: '' } }
            unreachable_code: { enabled: true }
            check_access_control: { enabled: true }
            typo_checks: { enabled: true }
            check_variables: { enabled: true }
            suspicious_code: { enabled: true, overriding_parameter: true, overriding_closure_use: true, parameter_closure_use_conflict: true, parameter_multiple_times: true, non_existent_class_in_instanceof_check: true, non_existent_class_in_catch_clause: true, assignment_of_null_return: true, non_commented_switch_fallthrough: true, non_commented_empty_catch_block: true, overriding_private_members: true, use_statement_alias_conflict: true, precedence_in_condition_assignment: true }
            dead_assignments: { enabled: true }
            verify_php_doc_comments: { enabled: true, parameters: true, return: true, suggest_more_specific_types: true, ask_for_return_if_not_inferrable: true, ask_for_param_type_annotation: true }
            loops_must_use_braces: { enabled: false }
            check_usage_context: { enabled: false, method_call_on_non_object: { enabled: false, ignore_null_pointer: false }, foreach: { value_as_reference: false, traversable: false }, missing_argument: false, argument_type_checks: disabled }
            simplify_boolean_return: { enabled: true }
            phpunit_checks: { enabled: false }
            reflection_checks: { enabled: false }
            precedence_checks: { enabled: false, assignment_in_condition: false, comparison_of_bit_result: false }
            basic_semantic_checks: { enabled: true }
            doc_comment_fixes: { enabled: true }
            reflection_fixes: { enabled: true }
            use_statement_fixes: { enabled: false, remove_unused: false, preserve_multiple: false, order_alphabetically: false }
    php_code_sniffer:
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
        config:
            standard: WordPress
            tab_width: '2'
            sniffs: { wordpress: { arrays: { array_declaration_sniff: true }, classes: { valid_class_name_sniff: true }, files: { file_name_sniff: true }, formatting: { multiple_statement_alignment_sniff: true }, functions: { function_call_signature_sniff: true, function_declaration_argument_spacing_sniff: true }, naming_conventions: { valid_function_name_sniff: true }, objects: { object_instantiation_sniff: true }, php: { discouraged_functions_sniff: true }, strings: { double_quote_usage_sniff: true }, white_space: { control_structure_spacing_sniff: true, operator_spacing_sniff: true, php_indent_sniff: true }, xss: { escape_output_sniff: true } } }
    sensiolabs_security_checker: true
    php_cpd:
        excluded_dirs:
            - lib
            - tests
            - languages
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
    php_loc:
        names:
            - 'inc/*.php'
        excluded_dirs:
            - lib
            - tests
    php_pdepend:
        excluded_dirs:
            - lib
            - tests
    php_code_coverage: true
