filter:
    excluded_paths: [tests/*, languages/*, lib/*, lib/Arabic/*]

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [tests, languages, lib]
    php_code_coverage: false
    php_code_sniffer:
        filter:
            excluded_paths: [tests/*, languages/*, lib/*]
        config:
            standard: WordPress
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
