filter:
    excluded_paths: [tests/*, assets/*, lib/*]

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [tests, lib]
    php_code_coverage: false
    php_code_sniffer: 
        excluded_dirs: [tests, lib]
    php_loc:
        excluded_dirs: [tests, lib]
    php_mess_detector: true
    php_pdepend:
        excluded_dirs: [tests, lib]
    php_analyzer:
        excluded_dirs: [tests, lib]
    sensiolabs_security_checker: true
