filter:
    paths:
        - 'inc/*'
        - '*'
    excluded_paths:
        - 'languages/*'
        - 'lib/*'
        - 'tests/*'
tools:
    php_mess_detector:
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
        config:
            unused_code_rules: { unused_formal_parameter: true }
            controversial_rules: { superglobals: false }
            design_rules: { exit_expression: false }
    php_analyzer:
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
    php_code_sniffer:
        command: 'phpcs -n -s -p -v'
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
        config:
            tab_width: '2'
            standard: WordPress
            sniffs: { psr1: { files: { side_effects_sniff: false } }, generic: { code_analysis: { for_loop_with_test_function_call_sniff: false, empty_statement_sniff: false, unnecessary_final_modifier_sniff: false, useless_overriding_method_sniff: false, jumbled_incrementer_sniff: false }, php: { deprecated_functions_sniff: false, character_before_php_opening_tag_sniff: false } }, squiz: { scope: { static_this_usage_sniff: false, method_scope_sniff: false, member_var_scope_sniff: false }, classes: { self_member_reference_sniff: false }, php: { non_executable_code_sniff: false } }, wordpress: { arrays: { array_declaration_sniff: true }, classes: { valid_class_name_sniff: true }, files: { file_name_sniff: true }, formatting: { multiple_statement_alignment_sniff: true }, functions: { function_call_signature_sniff: true, function_declaration_argument_spacing_sniff: true }, naming_conventions: { valid_function_name_sniff: true }, objects: { object_instantiation_sniff: true }, php: { discouraged_functions_sniff: true }, strings: { double_quote_usage_sniff: true }, white_space: { control_structure_spacing_sniff: true, operator_spacing_sniff: true, php_indent_sniff: true }, xss: { escape_output_sniff: true } } }
    sensiolabs_security_checker:
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
    php_cpd:
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
    php_pdepend:
        excluded_dirs:
            - languages
            - lib
            - tests
               