filter:
    paths:
        - 'inc/*'
        - '*'
    excluded_paths:
        - 'languages/*'
        - 'lib/*'
        - 'tests/*'
tools:
    php_mess_detector:
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
    php_code_sniffer:
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
        config:
            standard: WordPress
            tab_width: '2'
            sniffs: { wordpress: { arrays: { array_declaration_sniff: true }, classes: { valid_class_name_sniff: true }, files: { file_name_sniff: true }, formatting: { multiple_statement_alignment_sniff: true }, functions: { function_call_signature_sniff: true, function_declaration_argument_spacing_sniff: true }, naming_conventions: { valid_function_name_sniff: true }, objects: { object_instantiation_sniff: true }, php: { discouraged_functions_sniff: true }, strings: { double_quote_usage_sniff: true }, white_space: { control_structure_spacing_sniff: true, operator_spacing_sniff: true, php_indent_sniff: true }, xss: { escape_output_sniff: true } } }
    sensiolabs_security_checker: true
    php_cpd:
        excluded_dirs:
            - lib
            - tests
            - languages
        filter:
            excluded_paths: ['languages/*', 'lib/*', 'tests/*']
    php_loc:
        names:
            - 'inc/*.php'
        excluded_dirs:
            - lib
            - tests
    php_pdepend:
        excluded_dirs:
            - lib
            - tests
